#pragma checksum "..\..\Voyage.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "2FED5BBB18275B82EB3705382F92B1660499B80B"
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using BoatReservation;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace BoatReservation {
    
    
    /// <summary>
    /// Voyage
    /// </summary>
    public partial class Voyage : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 8 "..\..\Voyage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal BoatReservation.Voyage windowsVoyage;
        
        #line default
        #line hidden
        
        
        #line 12 "..\..\Voyage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label NavigationLabel;
        
        #line default
        #line hidden
        
        
        #line 13 "..\..\Voyage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BoatSection;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\Voyage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button PassengerSection;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\Voyage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button VoyageSection;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\Voyage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button HomeSection;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\Voyage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ReservationSection;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\Voyage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button LogoutSection;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/BoatReservation;component/voyage.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\Voyage.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.windowsVoyage = ((BoatReservation.Voyage)(target));
            
            #line 8 "..\..\Voyage.xaml"
            this.windowsVoyage.Closing += new System.ComponentModel.CancelEventHandler(this.windowsVoyage_Closing);
            
            #line default
            #line hidden
            return;
            case 2:
            this.NavigationLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 3:
            this.BoatSection = ((System.Windows.Controls.Button)(target));
            
            #line 13 "..\..\Voyage.xaml"
            this.BoatSection.Click += new System.Windows.RoutedEventHandler(this.BoatSection_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.PassengerSection = ((System.Windows.Controls.Button)(target));
            
            #line 14 "..\..\Voyage.xaml"
            this.PassengerSection.Click += new System.Windows.RoutedEventHandler(this.PassengerSection_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.VoyageSection = ((System.Windows.Controls.Button)(target));
            
            #line 15 "..\..\Voyage.xaml"
            this.VoyageSection.Click += new System.Windows.RoutedEventHandler(this.VoyageSection_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.HomeSection = ((System.Windows.Controls.Button)(target));
            
            #line 16 "..\..\Voyage.xaml"
            this.HomeSection.Click += new System.Windows.RoutedEventHandler(this.HomeSection_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.ReservationSection = ((System.Windows.Controls.Button)(target));
            return;
            case 8:
            this.LogoutSection = ((System.Windows.Controls.Button)(target));
            
            #line 18 "..\..\Voyage.xaml"
            this.LogoutSection.Click += new System.Windows.RoutedEventHandler(this.LogoutSection_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

